<?php
namespace App\Models;

use App\Core\Database;

class SplitJobFile {
    /**
     * Insert a new split chunk file record.
     *
     * @param array $data
     * @return array|null The inserted row
     */
    public static function create(array $data): ?array {
        $fields = array_keys($data);
        $placeholders = array_map(fn($f) => ":{$f}", $fields);
        
        $sql = "INSERT INTO split_job_files (" . implode(', ', $fields) . ", created_at, updated_at) 
                VALUES (" . implode(', ', $placeholders) . ", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                RETURNING *";

        return Database::fetch($sql, $data);
    }

    /**
     * Get all output chunk files generated by a parent split job.
     *
     * @param int $jobId
     * @return array
     */
    public static function getFilesByJobId(int $jobId): array {
        $sql = "SELECT * FROM split_job_files WHERE split_job_id = :job_id ORDER BY id ASC";
        return Database::fetchAll($sql, ['job_id' => $jobId]);
    }
}
